<?php

namespace Tests\Feature\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use App\Models\User;
use App\Eunms\User\UserType;
use App\Eunms\User\UserStatus;
use Tests\TestCase;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\UploadedFile;


class AuthorManagementTest extends TestCase
{
    use RefreshDatabase;

    protected User $admin;

    protected function setUp(): void
    {
        parent::setUp();
        
        // Create the admin user once for all tests in this class
        $this->admin = User::factory()->create([
            'type' => UserType::Admin,
            'status' => UserStatus::Active,
        ]);
    }

    /** @test */

    public function an_admin_can_create_an_author_with_an_avatar()
    {
        Storage::fake('public');

        $payload = [
            'username'   => 'test_author',
            'first_name' => 'Naguib',
            'last_name'  => 'Mahfouz',
            'email'      => 'naguib@example.com',
            'password'   => 'password123',
            'bio'        => 'Famous Egyptian writer.',
            'country'    => 'Egypt',
            'photo'      => UploadedFile::fake()->image('avatar.jpg')
        ];

        $response = $this->actingAs($this->admin, 'sanctum')
            ->postJson('/api/v1/admin/authors', $payload);

        $response->assertStatus(201)
                 ->assertJsonPath('data.username', 'test_author');

        $this->assertDatabaseHas('users', ['username' => 'test_author']);
        $this->assertDatabaseHas('authors', ['country' => 'Egypt']);
        
        // Assert storage using the hashName generated by Laravel
        $avatarName = $payload['photo']->hashName();
        Storage::disk('public')->assertExists("authors/avatars/{$avatarName}");
    }

    /** @test */

    public function the_live_search_returns_correct_results_by_full_name()
    {
        // Setup: Create specific authors
        User::factory()->create([
            'first_name' => 'Naguib', 
            'last_name' => 'Mahfouz', 
            'type' => UserType::Author,
            'status' => UserStatus::Active
        ]);

        User::factory()->create([
            'first_name' => 'Elif', 
            'last_name' => 'Shafak', 
            'type' => UserType::Author,
            'status' => UserStatus::Active
        ]);

        $response = $this->actingAs($this->admin, 'sanctum')
            ->getJson('/api/v1/admin/authors?search=Naguib');

        $response->assertStatus(200)
                 ->assertJsonCount(1, 'data.data')
                 ->assertJsonPath('data.data.0.firsrt_name', 'Naguib'); // Matches your resource typo 'firsrt_name'
    }
}